version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server/app/models:/app/app/models
      - ./reports:/app/reports
    depends_on:
      - redis
      - celery

  celery:
    build: ./server
    command: celery -A app.tasks.celery worker --loglevel=info
    volumes:
      - ./server/app:/app/app
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"