version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery_worker:
    build:
      context: ./backend
    command: celery -A app.celery_worker worker --loglevel=info
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/reports:/app/reports
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
