version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://server:8000

  server:
    build: ./server
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./reports:/app/reports

  worker:
    build: ./server
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"